DROP DATABASE IF EXISTS videotips;
DROP USER IF EXISTS 'admin'@'%';
DROP USER IF EXISTS 'noAdmin'@'%';
CREATE DATABASE IF NOT EXISTS videotips CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'alex';
GRANT SELECT, INSERT , UPDATE, DELETE ,CREATE,
	  DROP, REFERENCES, INDEX,ALTER,EXECUTE,
      CREATE VIEW,SHOW VIEW,CREATE ROUTINE, EVENT, 
      TRIGGER ON videotips.* TO 'admin'@'%';
CREATE USER IF NOT EXISTS 'noAdmin'@'%' IDENTIFIED BY 'alex';
GRANT SELECT, INSERT , UPDATE , DELETE, SHOW VIEW ON videotips.* TO 'noAdmin'@'%';
FLUSH PRIVILEGES;
SHOW DATABASES;
